plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: pconrad/ucsb-cs-jekyll-theme-try2

url: https://ucsb-cs111.github.io # the base hostname & protocol for your site
baseurl: "/"  # the subpath of your site, e.g. "/blog"

course: "CS111"
course_title: "Introduction to Computational Science"

kramdown:
   parse_block_html: false

title: "UCSB CS111"
github_url: https://github.com/ucsb-cs111/ucsb-cs111.github.io


exclude:
  - 'vendor'
  - 'setup.sh'
  - 'jekyll.sh'

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/

  textbooks:
    output: true
    permalink: /textbooks/:path/

  resources:
    output: true
    permalink: /resources/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: default

  - scope:
      path: ""
      type: resources
    values:
      layout: default

include:
  - _pages

